<?php
return array(
	'IMAGE_VERIFY_WIDTH' => 50,
	'IMAGE_VERIFY_HEIGHT' => 28,
	'IMAGE_VERIFY_FONTSIZE' => 16,
	'IMAGE_VERIFY_LENGTH' => 3,
	'IMAGE_VERIFY_USENOISE' => true,
	'IMAGE_VERIFY_CODESET' => '0123456789',
	'IMAGE_VERIFY_SETKEY' => 'md5'
);
?>